import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const kanit = Kanit({ subsets: ["latin"], weight: ["400", "500"] });

export const metadata: Metadata = {
  title: "Swanand Deshpande",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={kanit.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
